# Generated by Django 4.0.2 on 2022-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('deadlift', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bench_press', models.DecimalField(decimal_places=2, max_digits=4)),
                ('overhead_press', models.DecimalField(decimal_places=2, max_digits=4)),
                ('record_date', models.DateField()),
            ],
        ),
    ]
